### ISSUE TITLE
Long-Term Roadmap:

### ISSUE THREAD

**Issue by mizlan** [uclaacm/TeachLAFrontend#1055]
- [ ] (Incremental) Migration to TypeScript
- [ ] Incorporate a component library for consistent UI (e.g., Mantine UI) (can also be incrementally adopted)
    - Eventually drop Bootstrap as a dependency
- [ ] Rewrite all tests with React Testing Library and drop Enzyme as a dependency
- [ ] Switch from Redux `map{State,Dispatch}ToProps` to `useSelector` and `useDispatch`

**Comment by mizlan** [comment]
Current state:

- We have successfully migrated ~20% of the codebase to TypeScript.
- No component library, also might not be the best idea. Can use shadcn/ui if we ever incorporate Tailwind. Maybe drop bootstrap as a dependency as well.
- Just deleted all tests. The tests weren't really helpful anyway.
- Redux modernization is the biggest next goal.
